apiVersion: v1
kind: Config
current-context: smoke
contexts:
- name: smoke
  context:
    cluster: smoke
    user: smoke
clusters:
- name: smoke
  cluster:
    server: https://127.0.0.1:65535
    insecure-skip-tls-verify: true
users:
- name: smoke
  user:
    token: smoke
